apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-kubects-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-boot-kubects-demo
  template:
    metadata:
      labels:
        app: spring-boot-kubects-demo
    spec:
      containers:
        - name: spring-boot-kubects-demo
          image: spring-boot-kubects-demo:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
